# Generated by Django 5.2.8 on 2025-11-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0012_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(default=None, upload_to='about/'),
            preserve_default=False,
        ),
    ]
